var key=[];
key.push({
    source:"arrowUp.png",
    isSelectable:true,
    selector:{
        type:"key",
        color:"red",
        offsetX:1280,
        offsetY:760,
        width:95,
        height:95,
        description:"undefined"
    },
    onMouseOver(){
        drawRect(2,this.selector.color,this.selector.offsetX+2,this.selector.offsetY+2,this.selector.width-4,this.selector.height-4);
    },
    onClick(){
        playerTurn("move","w");
    }
})
key.push({
    source:"arrowDown.png",
    isSelectable:true,
    selector:{
        type:"key",
        color:"red",
        offsetX:1280,
        offsetY:860,
        width:95,
        height:95,
        description:"undefined"
    },
    onMouseOver(){
        drawRect(2,this.selector.color,this.selector.offsetX+2,this.selector.offsetY+2,this.selector.width-4,this.selector.height-4);
    },
    onClick(){
        playerTurn("move","s");
    }
})
key.push({
    source:"arrowLeft.png",
    isSelectable:true,
    selector:{
        type:"key",
        color:"red",
        offsetX:1180,
        offsetY:860,
        width:95,
        height:95,
        description:"undefined"
    },
    onMouseOver(){
        drawRect(2,this.selector.color,this.selector.offsetX+2,this.selector.offsetY+2,this.selector.width-4,this.selector.height-4);
    },
    onClick(){
        playerTurn("move","a");
    }
})
key.push({
    source:"arrowRight.png",
    isSelectable:true,
    selector:{
        type:"key",
        color:"red",
        offsetX:1380,
        offsetY:860,
        width:95,
        height:95,
        description:"undefined"
    },
    onMouseOver(){
        drawRect(2,this.selector.color,this.selector.offsetX+2,this.selector.offsetY+2,this.selector.width-4,this.selector.height-4);
    },
    onClick(){
        playerTurn("move","d");
    }
})