var character=new Map();

character.set("Lagrange",{
    id:"Lagrange",
    source:"Lagrange.jpg",
    mhp:150,
    mmp:80,
    atk:20,
    def:5,
    mat:20,
    mdf:5,
    atkR:2,
    isSelectable:true,
    selector:{
        type:"character",
        color:"red",
        offsetX:50,
        offsetY:100,
        width:100,
        height:100,
        description:{
            id:"Lagrange",
            icon:"Lagrange.jpg",
            text:`住在世界底层的研究者，前来“观察”迷宫。`,
        }
    },
    onClick(){
        setCharacter(this);
        if(currentStage=="prologue"){
            currentStage="battle";
            beginRound();
        }
    },
    onMouseOver(){
        drawRect(2,this.selector.color,this.selector.offsetX,this.selector.offsetY,this.selector.width,this.selector.height);
        displayDescription(this);
    }
});
character.set("Tairitsu",{
    id:"Tairitsu",
    source:"Tairitsu.png",
    mhp:100,
    mmp:100,
    atk:27,
    def:5,
    mat:25,
    mdf:5,
    atkR:2,
    isSelectable:true,
    selector:{
        type:"character",
        color:"red",
        offsetX:200,
        offsetY:100,
        width:100,
        height:100,
        description:{
            id:"Tairitsu",
            icon:"Tairitsu.png",
            text:`黑暗常伴的少女。`,
        }
    },
    onClick(){
        setCharacter(this);
        giveEffect(player,"revival",1,true);
        if(currentStage=="prologue"){
            currentStage="battle";
            beginRound();
        }
    },
    onMouseOver(){
        drawRect(2,this.selector.color,this.selector.offsetX,this.selector.offsetY,this.selector.width,this.selector.height);
        displayDescription(this);
    }
});
character.set("Tairitsu-Tempest",{
    id:"Tairitsu-Tempest",
    source:"Tairitsu.png",
    mhp:300,
    mmp:300,
    atk:50,
    def:5,
    mat:50,
    mdf:5,
    atkR:4,
    isSelectable:false,
    selector:{
        type:"character",
        color:"red",
        offsetX:200,
        offsetY:100,
        width:0,
        height:0,
        description:{
            id:"Tairitsu",
            icon:"Tairitsu.png",
            text:`她是迫近的风暴。`,
        }
    },
    onClick(){
        setCharacter(this);
    },
    onMouseOver(){
        drawRect(2,this.selector.color,this.selector.offsetX,this.selector.offsetY,this.selector.width,this.selector.height);
        displayDescription(this);
    }
});
character.set("Hikari",{
    id:"Hikari",
    source:"Hikari.png",
    mhp:200,
    mmp:100,
    atk:10,
    def:0,
    mat:40,
    mdf:0,
    atkR:1,
    isSelectable:true,
    selector:{
        type:"character",
        color:"red",
        offsetX:350,
        offsetY:100,
        width:100,
        height:100,
        description:{
            id:"Hikari",
            icon:"Hikari.png",
            text:`光芒常伴的少女。`,
        }
    },
    onClick(){
        setCharacter(this);
        if(currentStage=="prologue"){
            currentStage="battle";
            beginRound();
        }
    },
    onMouseOver(){
        drawRect(2,this.selector.color,this.selector.offsetX,this.selector.offsetY,this.selector.width,this.selector.height);
        displayDescription(this);
    }
});

function setCharacter(charId){
    let chara;
    if(typeof charId=="object") chara=charId;
    if(typeof charId=="string") chara=character.get(charId);
    console.log(chara);
    player.source=chara.source;
    player.baseMhp=chara.mhp;
    player.baseMmp=chara.mmp;
    player.baseDef=chara.def;
    player.baseAtk=chara.atk;
    player.baseMat=chara.mat;
    player.baseMdf=chara.mdf;
    player.baseAtkR=chara.atkR;
    player.selector.description.icon=chara.selector.description.icon;
    player.selector.description.id=chara.id;
    player.selector.description.text=chara.selector.description.text;
    updatePlayerStat();
    checkPlayerStat();
}