var choiceSlot=[];
choiceSlot.push({
    id:1,
    choiceId:-1,
    isSelectable:true,
    selector:{
        type:"choice",
        color:"red",
        offsetX:50,
        offsetY:100,
        width:300,
        height:450,
        description:{
            id:1,
            icon:"undefined",
            text:"undefined",
        }
    },
    onMouseOver(){
        drawRect(2,this.selector.color,this.selector.offsetX+2,this.selector.offsetY+2,this.selector.width-4,this.selector.height-4);
    },
    onClick(){
        choose(this.choiceId);
        intermissonPage();
    }
})
choiceSlot.push({
    id:2,
    choiceId:-1,
    isSelectable:true,
    selector:{
        type:"choice",
        color:"red",
        offsetX:375,
        offsetY:100,
        width:300,
        height:450,
        description:{
            id:1,
            icon:"undefined",
            text:"undefined",
        }
    },
    onMouseOver(){
        drawRect(2,this.selector.color,this.selector.offsetX+2,this.selector.offsetY+2,this.selector.width-4,this.selector.height-4);
    },
    onClick(){
        choose(this.choiceId);
        intermissonPage();
    }
})
choiceSlot.push({
    id:3,
    choiceId:-1,
    isSelectable:true,
    selector:{
        type:"choice",
        color:"red",
        offsetX:700,
        offsetY:100,
        width:300,
        height:450,
        description:{
            id:1,
            icon:"undefined",
            text:"undefined",
        }
    },
    onMouseOver(){
        drawRect(2,this.selector.color,this.selector.offsetX+2,this.selector.offsetY+2,this.selector.width-4,this.selector.height-4);
    },
    onClick(){
        choose(this.choiceId);
        intermissonPage();
    }
})