var skillType=new Map();
skillType.set("fireball",{
    id:"fireball",
    spell:fireball,
    cost:5,
    cd:2,
    source:"fireball.png",
    sourceCD:"fireball-cd.png",
    targetSelector(){
        traceSelector(player);
    },
    isSelectable:true,
    selector:{
        type:"skillSlot",
        color:"red",
        offsetX:0,
        offsetY:0,
        width:0,
        height:0,
        description:{
            id:"fireball",
            icon:"fireball.png",
            text:"能对一定范围内敌人造成伤害的火球。"
        }
    },
    onMouseOver(){
        ;
    },
    onClick(){
        ;
    }
});
skillType.set("flashmove",{
    id:"flashmove",
    spell:flashmove,
    cost:5,
    cd:3,
    source:"flash.png",
    sourceCD:"flash-cd.png",
    targetSelector(){
        return;
    },
    isSelectable:true,
    selector:{
        type:"skillSlot",
        color:"red",
        offsetX:0,
        offsetY:0,
        width:0,
        height:0,
        description:{
            id:"flashmove",
            icon:"flash.png",
            text:"瞬间移动到任意合法位置！"
        }
    },
    onMouseOver(){
        ;
    },
    onClick(){
        ;
    }
});
skillType.set("sacriStrike",{
    id:"sacriStrike",
    spell:sacrificialStrike,
    cost:0,
    cd:9,
    source:"sacriPunch.png",
    sourceCD:"sacriPunch-cd.png",
    targetSelector:sacriStrikeSelector,
    isSelectable:true,
    selector:{
        type:"skillSlot",
        color:"red",
        offsetX:0,
        offsetY:0,
        width:0,
        height:0,
        description:{
            id:"sacrificialStrike",
            icon:"sacriPunch.png",
            text:"以20%的hp为代价，对周围所有敌人造成大额伤害。"
        }
    },
    onMouseOver(){
        ;
    },
    onClick(){
        ;
    }
});
skillType.set("heal",{
    id:"heal",
    spell:heal,
    cost:10,
    cd:6,
    source:"heal.png",
    sourceCD:"heal-cd.png",
    targetSelector(){
        return;
    },
    isSelectable:true,
    selector:{
        type:"skillSlot",
        color:"red",
        offsetX:0,
        offsetY:0,
        width:0,
        height:0,
        description:{
            id:"heal",
            icon:"heal.png",
            text:"恢复你的hp"
        }
    },
    onMouseOver(){
        ;
    },
    onClick(){
        ;
    }
});